"""契约层模型、版本常量与 normalize_* 归一化函数的对外导出。"""
from shared_backend.case_ids import (
    build_case_metadata,
    build_case_id,
    build_case_prefix,
    infer_case_type,
    infer_client_code,
    infer_module_code,
    infer_page_code,
    infer_source_code,
    match_case_id,
    next_case_sequence,
    normalize_case_id,
    slugify_case_part,
    split_run_id,
)
from .contracts import (
    EVIDENCE_MANIFEST_VERSION,
    EXECUTION_RECORD_VERSION,
    LEGACY_EVIDENCE_SCHEMA_VERSION,
    PAGE_ANALYSIS_BUNDLE_VERSION,
    PAGE_OBJECT_DRAFT_VERSION,
    PAGE_SEMANTIC_MODEL_VERSION,
    PAGE_SURFACE_VERSION,
    TEST_POINT_PLAN_VERSION,
    normalize_evidence_manifest_v1,
    normalize_execution_record_v1,
    normalize_page_analysis_bundle_v1,
    normalize_page_object_draft_v1,
    normalize_page_semantic_model_v1,
    normalize_page_surface_v1,
    normalize_test_point_plan_v1,
)
from .models import (
    ALLOWED_ACTIONS,
    VALID_SOURCE_TYPES,
    DependencyReviewEntryV1,
    DependencyReviewV1,
    PageElementMapping,
    PageObjectV1,
    QualityGateThresholds,
    TestPointPlanV1,
    TestPointStepV1,
    TestPointV1,
)
from .validator import ContractValidator, ValidationResult

__all__ = [
    "ALLOWED_ACTIONS",
    "ContractValidator",
    "EVIDENCE_MANIFEST_VERSION",
    "EXECUTION_RECORD_VERSION",
    "LEGACY_EVIDENCE_SCHEMA_VERSION",
    "PAGE_ANALYSIS_BUNDLE_VERSION",
    "PAGE_OBJECT_DRAFT_VERSION",
    "PAGE_SEMANTIC_MODEL_VERSION",
    "PAGE_SURFACE_VERSION",
    "TEST_POINT_PLAN_VERSION",
    "VALID_SOURCE_TYPES",
    "DependencyReviewEntryV1",
    "DependencyReviewV1",
    "PageElementMapping",
    "PageObjectV1",
    "QualityGateThresholds",
    "TestPointPlanV1",
    "TestPointStepV1",
    "TestPointV1",
    "ValidationResult",
    "normalize_evidence_manifest_v1",
    "normalize_execution_record_v1",
    "normalize_page_analysis_bundle_v1",
    "normalize_page_object_draft_v1",
    "normalize_page_semantic_model_v1",
    "normalize_page_surface_v1",
    "normalize_test_point_plan_v1",
]
