"""Shared backend contracts and utilities."""

from .case_ids import (
    build_case_metadata,
    build_case_id,
    build_case_prefix,
    infer_case_type,
    infer_client_code,
    infer_module_code,
    infer_page_code,
    infer_source_code,
    match_case_id,
    next_case_sequence,
    normalize_case_id,
    slugify_case_part,
    split_run_id,
)
from .case_dictionary import (
    get_alias_code_map,
    get_code_name_map,
    get_dictionary_items,
    load_case_dictionaries,
    resolve_dictionary_code,
    resolve_dictionary_name,
)
from .case_rules import (
    CaseRuleViolation,
    enrich_case_metadata,
    validate_case_description,
    validate_case_payload,
    validate_case_title,
)
from .state_machines import (
    get_ai_status_name,
    get_case_status_name,
    get_run_status_name,
    normalize_ai_status,
    normalize_case_status,
    normalize_run_status,
    validate_state_transition,
)

__all__ = [
    "build_case_metadata",
    "build_case_id",
    "build_case_prefix",
    "infer_case_type",
    "infer_client_code",
    "infer_module_code",
    "infer_page_code",
    "infer_source_code",
    "match_case_id",
    "next_case_sequence",
    "normalize_case_id",
    "slugify_case_part",
    "split_run_id",
    "get_alias_code_map",
    "get_code_name_map",
    "get_dictionary_items",
    "load_case_dictionaries",
    "resolve_dictionary_code",
    "resolve_dictionary_name",
    "CaseRuleViolation",
    "enrich_case_metadata",
    "validate_case_description",
    "validate_case_payload",
    "validate_case_title",
    "get_ai_status_name",
    "get_case_status_name",
    "get_run_status_name",
    "normalize_ai_status",
    "normalize_case_status",
    "normalize_run_status",
    "validate_state_transition",
]
