#!/usr/bin/env python3
"""
拆分 legacy_workbench.py 脚本
用途：将 8876 行的大文件拆分为可维护的模块结构
"""

import re
import sys
from pathlib import Path
from typing import Optional

# 文件路径
REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_FILE = REPO_ROOT / "apps/web-ui-service/app/routers/legacy_workbench.py"
TARGET_DIR = REPO_ROOT / "apps/web-ui-service/app/routers/legacy_workbench"

def read_source() -> str:
    """读取源文件"""
    with open(SOURCE_FILE, 'r', encoding='utf-8') as f:
        return f.read()

def extract_section(content: str, pattern: str, description: str) -> tuple[str, str]:
    """提取匹配的内容，返回 (提取的内容，剩余内容)"""
    match = re.search(pattern, content, re.MULTILINE | re.DOTALL)
    if match:
        extracted = match.group(0)
        remaining = content[:match.start()] + content[match.end():]
        print(f"   ✅ 提取 {description}: {len(extracted.splitlines())} 行")
        return extracted, remaining
    return "", content

def main():
    if not SOURCE_FILE.exists():
        print(f"❌ 源文件不存在：{SOURCE_FILE}")
        return 1
    
    print(f"📄 读取源文件：{SOURCE_FILE}")
    content = read_source()
    total_lines = len(content.splitlines())
    print(f"   总行数：{total_lines}")
    
    # 创建目标目录
    print(f"\n📁 创建目标目录：{TARGET_DIR}")
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    (TARGET_DIR / "utils").mkdir(exist_ok=True)
    (TARGET_DIR / "services").mkdir(exist_ok=True)
    (TARGET_DIR / "handlers").mkdir(exist_ok=True)
    
    # 1. 提取 imports
    print("\n1️⃣  提取 imports...")
    imports_match = re.match(r'^(.*?)(?=\n\nclass |\n\n@router\.)', content, re.DOTALL)
    if imports_match:
        imports_section = imports_match.group(1)
        print(f"   ✅ 提取 imports: {len(imports_section.splitlines())} 行")
    else:
        imports_section = ""
        print("   ⚠️  未找到 imports 块")
    
    # 2. 提取 Pydantic 模型
    print("\n2️⃣  提取 Pydantic 模型...")
    models_pattern = r'^(\nclass \w+\(BaseModel\):.*?)(?=\n\ndef |^@router\.)'
    models_matches = re.findall(models_pattern, content, re.MULTILINE | re.DOTALL)
    models_section = "\n\n".join(models_matches) if models_matches else ""
    print(f"   ✅ 提取模型：{len(models_matches)} 个类")
    
    # 3. 提取路由定义
    print("\n3️⃣  提取路由定义...")
    router_pattern = r'^(@router\.[^\n]+\n(?:async )?def \w+\([^)]*\)[^:]*:.*?)(?=\n@router\.|\Z)'
    router_matches = re.findall(router_pattern, content, re.MULTILINE | re.DOTALL)
    print(f"   ✅ 提取路由：{len(router_matches)} 个")
    
    # 4. 提取工具函数
    print("\n4️⃣  提取工具函数...")
    func_pattern = r'^(\ndef _\w+\([^)]*\)[^:]*:.*?)(?=\n(?:def |async def |@router\.|\Z))'
    func_matches = re.findall(func_pattern, content, re.MULTILINE | re.DOTALL)
    print(f"   ✅ 提取工具函数：{len(func_matches)} 个")
    
    # 生成报告
    print("\n📊 分析结果:")
    print("=" * 60)
    print(f"源文件：{total_lines} 行")
    print(f"Pydantic 模型：{len(models_matches)} 个")
    print(f"API 路由：{len(router_matches)} 个")
    print(f"工具函数：{len(func_matches)} 个")
    print("=" * 60)
    
    # 询问是否继续
    print("\n⚠️  这个脚本会创建新的目录结构，但不会删除原文件。")
    print("   是否继续？(y/n): ", end='')
    if len(sys.argv) > 1 and sys.argv[1] == '--force':
        confirm = 'y'
        print('y (自动确认)')
    else:
        confirm = input().strip().lower()
    
    if confirm != 'y':
        print("\n❌ 已取消")
        return 0
    
    # 创建 __init__.py 文件
    print("\n📝 创建模块文件...")
    
    # utils/__init__.py
    (TARGET_DIR / "utils/__init__.py").write_text("# Utils module\n", encoding='utf-8')
    
    # services/__init__.py
    (TARGET_DIR / "services/__init__.py").write_text("# Services module\n", encoding='utf-8')
    
    # handlers/__init__.py
    (TARGET_DIR / "handlers/__init__.py").write_text("# Handlers module\n", encoding='utf-8')
    
    # models.py
    models_file = TARGET_DIR / "models.py"
    models_content = f'"""Pydantic models for legacy workbench."""\n\nfrom pydantic import BaseModel, Field\n\n{models_section}'
    models_file.write_text(models_content, encoding='utf-8')
    print(f"   ✅ 创建 models.py: {len(models_content.splitlines())} 行")
    
    # router.py (主路由文件)
    router_file = TARGET_DIR / "router.py"
    router_content = f'''"""Legacy workbench router.

This module is auto-generated by split-workbench.py
Original file: {SOURCE_FILE.name} ({total_lines} lines)
"""

{imports_section}

from .models import *
from .utils.helpers import *
from .utils.review_helpers import *
from .utils.execution_gate import *
from .utils.runtime_manager import *
from .utils.quality_gate import *
from .services.case_generator import *
from .services.test_point_manager import *
from .services.run_executor import *
from .services.report_service import *
from .handlers.review_handler import *
from .handlers.execution_gate_handler import *
from .handlers.run_handler import *

router = APIRouter(tags=["legacy-workbench"])

# TODO: Move router definitions here from original file
# There are {len(router_matches)} routes to migrate

# Example:
# @router.get("/api/workbench/projects")
# async def get_projects(...):
#     ...
'''
    router_file.write_text(router_content, encoding='utf-8')
    print(f"   ✅ 创建 router.py: {len(router_content.splitlines())} 行")
    
    # 创建占位文件
    placeholder_files = [
        "utils/helpers.py",
        "utils/review_helpers.py",
        "utils/execution_gate.py",
        "utils/runtime_manager.py",
        "utils/quality_gate.py",
        "services/case_generator.py",
        "services/test_point_manager.py",
        "services/run_executor.py",
        "services/report_service.py",
        "handlers/review_handler.py",
        "handlers/execution_gate_handler.py",
        "handlers/run_handler.py",
    ]
    
    for placeholder in placeholder_files:
        file_path = TARGET_DIR / placeholder
        module_name = placeholder.replace('/', '.').replace('.py', '')
        content = f'''"""{module_name.replace('_', ' ').title()}"""

# TODO: Migrate functions from {SOURCE_FILE.name}
# This is a placeholder file created by split-workbench.py
'''
        file_path.write_text(content, encoding='utf-8')
        print(f"   ✅ 创建 {placeholder}")
    
    # 生成迁移指南
    guide_file = TARGET_DIR / "MIGRATION_GUIDE.md"
    guide_content = f'''# Legacy Workbench 拆分迁移指南

## 概述

原文件：`legacy_workbench.py` ({total_lines} 行)  
新结构：`legacy_workbench/` 目录

## 新目录结构

```
legacy_workbench/
├── __init__.py
├── router.py                # 主路由 ({len(router_matches)} 个路由)
├── models.py                # Pydantic 模型 ({len(models_matches)} 个)
├── utils/
│   ├── helpers.py           # 通用工具函数
│   ├── review_helpers.py    # Review 相关
│   ├── execution_gate.py    # Execution Gate
│   ├── runtime_manager.py   # 运行时管理
│   └── quality_gate.py      # 质量门禁
├── services/
│   ├── case_generator.py    # 用例生成
│   ├── test_point_manager.py # 测试点管理
│   ├── run_executor.py      # 运行执行
│   └── report_service.py    # 报告服务
└── handlers/
    ├── review_handler.py    # Review 处理
    ├── execution_gate_handler.py # Gate 处理
    └── run_handler.py       # 运行处理
```

## 迁移步骤

### 第 1 步：工具函数分类 (约 2-3 小时)

将 `{len(func_matches)}` 个工具函数按功能分类：

| 函数前缀/功能 | 目标文件 | 预估数量 |
|--------------|----------|----------|
| `_review_*` | `utils/review_helpers.py` | ~20 |
| `_execution_gate_*` | `utils/execution_gate.py` | ~25 |
| `_runtime_*` | `utils/runtime_manager.py` | ~15 |
| `_quality_gate_*` | `utils/quality_gate.py` | ~15 |
| `_build_*` / `_extract_*` | `services/*` | ~30 |
| 其他 | `utils/helpers.py` | ~剩余 |

### 第 2 步：服务层提取 (约 2-3 小时)

按业务功能提取服务：

| 功能 | 目标文件 | 相关路由 |
|------|----------|----------|
| 用例生成 | `services/case_generator.py` | `/generate`, `/preview-test-points` |
| 测试点管理 | `services/test_point_manager.py` | `/test-point-assets` |
| 运行执行 | `services/run_executor.py` | `/run`, `/auto-run`, `/rerun` |
| 报告服务 | `services/report_service.py` | `/report/*` |

### 第 3 步：Handler 层提取 (约 1-2 小时)

将路由处理逻辑移到 handler：

| Handler | 负责的路由 |
|---------|-----------|
| `review_handler` | `/reviews` |
| `execution_gate_handler` | `/execution-gate/*` |
| `run_handler` | `/runs/*`, `/heal`, `/heal-and-rerun` |

### 第 4 步：更新 router.py (约 1 小时)

更新 `router.py` 导入和路由定义

### 第 5 步：测试验证 (约 2-3 小时)

- 运行现有测试
- 手动测试主要功能
- 修复导入问题

## 总预估时间：8-14 小时

## 注意事项

1. **保留原文件** - 拆分完成前不要删除原文件
2. **逐步迁移** - 每次迁移一个模块，测试通过后再继续
3. **导入修复** - 注意循环导入问题
4. **测试覆盖** - 确保现有测试仍然通过

## 回滚方案

如果拆分失败，删除新目录，使用原文件即可。
'''
    guide_file.write_text(guide_content, encoding='utf-8')
    print(f"\n📖 创建迁移指南：MIGRATION_GUIDE.md")
    
    print("\n" + "=" * 60)
    print("✅ 拆分框架创建完成!")
    print(f"📁 新目录：{TARGET_DIR}")
    print(f"📄 下一步：阅读 {guide_file} 开始迁移")
    print("=" * 60)
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
