from app.routers import (
    auth,
    dashboard,
    health,
    page_objects,
    page_objects_recorder,
    test_cases,
    test_projects,
    ui,
    workbench_assets,
    workbench_gate,
    workbench_generation,
    workbench_reporting,
    workbench_reviews,
    workbench_runs,
    workbench_scheduler,
    workbench_tasks,
)

__all__ = [
    "auth",
    "dashboard",
    "health",
    "page_objects",
    "page_objects_recorder",
    "test_cases",
    "test_projects",
    "ui",
    "workbench_assets",
    "workbench_gate",
    "workbench_generation",
    "workbench_reporting",
    "workbench_reviews",
    "workbench_runs",
    "workbench_scheduler",
    "workbench_tasks",
]
